name: budgee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^4.15.9
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_app_check: ^0.2.2+7
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  local_auth: ^2.2.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2

dev_dependencies:

  # Code generation
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
  # Example of custom font - we'll use Google Fonts too
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
